/* eslint-disable react-hooks/exhaustive-deps */
import { useState, useEffect, Fragment } from "react";
import { Row, Col, Image } from "react-bootstrap";
import { getCollection } from "../../../CRUD/collections.crud";

const AutogeneratedPage = ({ match }) => {
  // Constants
  const userId = match.params.userId;
  const collectionId = match.params.collectionId;
  const collectionName = match.params.name;

  // State Variables
  const [collection, setCollection] = useState();

  useEffect(() => {
    getCollectionResponse();
  }, []);

  // API to get all images stored in a particular collection
  const getCollectionResponse = async () => {
    const res = await getCollection(collectionId, userId);
    setCollection(res.data);
  };

  return (
    <Fragment>
      <Row>
        <Col className="text-center mt-3">
          {" "}
          <h3 className="w-100 mt-md-4 mt-2">{collectionName}</h3>
          <br />
          {collection && collection.length > 0 && (
            <Fragment>
              <Row>
                {collection.map((item, idx) => (
                  <Fragment>
                    <Col
                      sm={4}
                      lg={3}
                      xl={3}
                      md={4}
                      xs={6}
                      key={idx}
                      className="d-flex justify-content-center p-2"
                    >
                      <Image
                        className="image cursor-pointer w-100"
                        src={item.imageUrl}
                        alt="Images"
                        style={{ border: "2px solid #000000" }}
                      />
                    </Col>
                  </Fragment>
                ))}
              </Row>
            </Fragment>
          )}
          <div className="alert alert-dark text-center my-4" role="alert">
            This Page is managed by Image Dock and is auto generated.
          </div>
        </Col>
      </Row>
    </Fragment>
  );
};

export default AutogeneratedPage;
